apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "garden-shoot-trust-configurator.config.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "garden-shoot-trust-configurator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
immutable: true
data:
{{ include "garden-shoot-trust-configurator.config.data" . | indent 2 }}
