# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.kubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garden-shoot-trust-configurator.name" . }}-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "garden-shoot-trust-configurator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  kubeconfig: {{ required ".Values.kubeconfig is required" .Values.kubeconfig | b64enc }}
{{- end }}
