# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garden-shoot-trust-configurator.name" . }}-access-token
  namespace: {{ .Release.Namespace }}
  labels:
    resources.gardener.cloud/purpose: token-requestor
    resources.gardener.cloud/class: shoot
  annotations:
    serviceaccount.resources.gardener.cloud/name: {{ include "garden-shoot-trust-configurator.name" . }}
    serviceaccount.resources.gardener.cloud/namespace: {{ .Release.Namespace }}
type: Opaque
