# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garden-shoot-trust-configurator.name" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
type: Opaque
data:
  tls.crt: {{ required ".Values.global.webhooks.tls.crt is required" .Values.global.webhooks.tls.crt | b64enc }}
  tls.key: {{ required ".Values.global.webhooks.tls.key is required" .Values.global.webhooks.tls.key | b64enc }}
