# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "garden-shoot-trust-configurator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "garden-shoot-trust-configurator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.additionalAnnotations.service }}
  annotations:
    {{- toYaml .Values.additionalAnnotations.service | trim | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "garden-shoot-trust-configurator.name" . }}
  ports:
    - name: https
      port: 443
      targetPort: {{ .Values.config.server.port }}
      protocol: TCP
    - name: health
      port: 8081
      targetPort: {{ .Values.config.server.healthPort }}
      protocol: TCP
