# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "garden-shoot-trust-configurator.name" . }}
  labels:
{{ include "labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "garden-shoot-trust-configurator.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "garden-shoot-trust-configurator.name" . }}
  namespace: {{ .Release.Namespace }}
