# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: garden-shoot-trust-configurator
description: A Helm chart for Kubernetes that deploys the Garden Shoot Trust Configurator in the Garden cluster.
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: application
    version: 0.1.0
    condition: application.enabled
  - name: runtime
    version: 0.1.0
    condition: runtime.enabled
